### PR TITLE
Fix a few leaks

### PR DESCRIPTION
**Pull request by hadess**
2 memleak fixes discovered through Coverity.

### CODE REVIEW

**Comment by nikias** [comment]
The change in xplist.c will cause multiple checks to fail. The fix looked straight forward to me but I think it's not that simple.

**Comment by hadess** [comment]
> The change in xplist.c will cause multiple checks to fail. The fix looked straight forward to me but I think it's not that simple.

Did you find that out by running the test suite? I can try to figure out what it would take to fix it.

Is the other patch ok?

**Comment by nikias** [comment]
Yes, ```make check``` revealed it. The other patch is fine.

**Comment by hadess** [comment]
Couldn't figure out what the problem was after staring at it for a while. I've fixed a typo instead, and filed #122 about it.

**Pull request merged**
